### ISSUE TITLE
Does it work without GPU?

### ISSUE THREAD

**Issue by longwall** [dhlab-epfl/dhSegment#48]
Hello,
I have simple videocard on my working Win7 machine. Installed all needed reqs and stared demo.py
I got some error stack and wonder - does it refer to missing GPU or any incorrect installation procedure?

`(dh_segment) C:\p\Documents\ai\dhSegment>python demo.py
Traceback (most recent call last):
  File "C:\p\anaconda3\envs\dh_segment\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\p\anaconda3\envs\dh_segment\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\p\anaconda3\envs\dh_segment\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
   
 _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\p\anaconda3\envs\dh_segment\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\p\anaconda3\envs\dh_segment\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "demo.py", line 8, in <module>
    import tensorflow as tf
  File "C:\p\anaconda3\envs\dh_segment\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\p\anaconda3\envs\dh_segment\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\p\anaconda3\envs\dh_segment\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\p\anaconda3\envs\dh_segment\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\p\anaconda3\envs\dh_segment\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\p\anaconda3\envs\dh_segment\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\p\anaconda3\envs\dh_segment\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\p\anaconda3\envs\dh_segment\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.`

Could you please advice?  On my laptop with GPU I managed to start demo

**Comment by duncdrum** [comment]
I don't think it does, the fall back to tensorflow from tensorflow-gpu does not seem to work.

**Comment by longwall** [comment]
ok, thanks
