### ISSUE TITLE
OOTB syntax error with demo.py

### ISSUE THREAD

**Issue by duncdrum** [dhlab-epfl/dhSegment#51]
Following the installation instructions in the docs the final step: `python demo.py`

results in 
```
File "demo.py", line 20
    def page_make_binary_mask(probs: np.ndarray, threshold: float=-1) -> np.ndarray:
                                   ^
SyntaxError: invalid syntax
```

Similarly `python3 demo.py`

```
Traceback (most recent call last):
  File "demo.py", line 6, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
```

**Comment by duncdrum** [comment]
after some more testing: the `opencv-python` dependency does not get installed properly when running the `pip install git+https…` command of the installation instructions. 
`conda install` also doesn't do the trick, another `pip install opencv-python` inside the running conda session gets me further, but still leads to opencv related crashes.

Tested on alpine, debian, macOS.
